### PR TITLE
fixed bug

### PR DESCRIPTION
**Pull request by BjarneVerschorre**

### CODE REVIEW

**Comment by raccoondays** [comment]
Your `.gitignore` is not configured to work with a Python environment, please fix this.

**Comment by BjarneVerschorre** [comment]
You'r'e welcome

**Comment by raccoondays** [comment]
> 

Based, however I am not able to merge without you fixing this.

**Comment by BjarneVerschorre** [comment]
tis u rn, just merge

**Comment by raccoondays** [comment]
> tis u rn, just merge 

Assigned it to a junior developer. Closing issue.

**Pull request closed without merging**
